sudo: false
dist: trusty

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

env:
  - WOO_VERSION="3.5.7" WP_VERSION=latest

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

install:
  - cd /tmp
  - git clone https://github.com/woocommerce/woocommerce
  - cd woocommerce/
  - git checkout tags/$WOO_VERSION
  - bash tests/bin/install.sh woocommerce_test root '' localhost $WP_VERSION
  - cd ..
  - cd $TRAVIS_BUILD_DIR
  - composer require --dev phpunit/phpunit ^7

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then vendor/bin/phpunit ; else phpunit ; fi
    if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then WP_MULTISITE=1 vendor/bin/phpunit ; else phpunit ; fi

